#!/bin/bash
set -e

PERIOD="${1:-6m}"
POST_COMMENT="${2:-true}"

# git-vibe 실행 (JSON 출력)
RESULT=$(git-vibe --path "${GITHUB_WORKSPACE}" --period "${PERIOD}" --json)

# JSON에서 값 추출
VIBE_SCORE=$(echo "$RESULT" | jq -r '.vibe_score')
VIBE_GRADE=$(echo "$RESULT" | jq -r '.vibe_grade')
BUS_FACTOR=$(echo "$RESULT" | jq -r '.bus_factor')

# 서브 스코어 추출
FREQ=$(echo "$RESULT" | jq -r '.sub_scores.commit_frequency')
HOTSPOT=$(echo "$RESULT" | jq -r '.sub_scores.hotspot_score')
GHOST=$(echo "$RESULT" | jq -r '.sub_scores.ghost_score')
MOOD=$(echo "$RESULT" | jq -r '.sub_scores.mood_score')
BF_SCORE=$(echo "$RESULT" | jq -r '.sub_scores.bus_factor_score')
TREND=$(echo "$RESULT" | jq -r '.sub_scores.trend_score')

# Markdown 코멘트 생성
COMMENT="## 🎭 Vibe Check

**Overall Vibe: ${VIBE_GRADE} (${VIBE_SCORE}/100)**

| Metric | Score |
|--------|------:|
| Commit Frequency | ${FREQ} |
| Hotspot Health | ${HOTSPOT} |
| Ghost Files | ${GHOST} |
| Commit Mood | ${MOOD} |
| Bus Factor | ${BF_SCORE} |
| Activity Trend | ${TREND} |

🏋️ Bus Factor: ${BUS_FACTOR}

---
*Generated by [git-vibe](https://github.com/calintzy/git-vibe)*"

# GitHub Output 설정
echo "vibe-score=${VIBE_SCORE}" >> "$GITHUB_OUTPUT"
echo "vibe-grade=${VIBE_GRADE}" >> "$GITHUB_OUTPUT"

# PR 코멘트 게시
if [ "$POST_COMMENT" = "true" ] && [ -n "$GITHUB_TOKEN" ]; then
    if [ -n "$GITHUB_EVENT_PATH" ]; then
        PR_NUMBER=$(jq -r '.pull_request.number // empty' "$GITHUB_EVENT_PATH")
        if [ -n "$PR_NUMBER" ]; then
            PAYLOAD=$(jq -n --arg body "$COMMENT" '{"body": $body}')
            curl -s -X POST \
                -H "Authorization: token ${GITHUB_TOKEN}" \
                -H "Accept: application/vnd.github.v3+json" \
                "${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/comments" \
                -d "$PAYLOAD"
        fi
    fi
fi

echo "$COMMENT"
