use crate::git::AnalysisResult;
use crate::scoring::VibeScore;
use crate::scoring::grades::VibeGrade;

/// 등급별 테마 색상
fn grade_color(grade: &VibeGrade) -> &'static str {
    match grade {
        VibeGrade::Zen => "#4c1",
        VibeGrade::Chill => "#97CA00",
        VibeGrade::Active => "#dfb317",
        VibeGrade::Tense => "#fe7d37",
        VibeGrade::Stressed => "#e05d44",
        VibeGrade::Chaotic => "#e05d44",
        VibeGrade::Abandoned => "#9f9f9f",
    }
}

/// XML 특수문자 이스케이프
fn xml_escape(s: &str) -> String {
    s.replace('&', "&amp;")
     .replace('<', "&lt;")
     .replace('>', "&gt;")
     .replace('"', "&quot;")
}

/// 점수 바 SVG rect 생성 (0~100 → 0~200px 바)
fn score_bar_svg(label: &str, value: f64, y: u32, bar_color: &str) -> String {
    let bar_width = 200u32;
    let filled = ((value / 100.0) * bar_width as f64).round() as u32;
    let bar_y = y - 12;
    format!(
        r##"  <text x="40" y="{y}" fill="#c0caf5" font-size="14" font-family="system-ui">{label}</text>
  <rect x="220" y="{bar_y}" width="{bar_width}" height="16" rx="4" fill="#2a2b3d"/>
  <rect x="220" y="{bar_y}" width="{filled}" height="16" rx="4" fill="{bar_color}"/>
  <text x="430" y="{y}" fill="#c0caf5" font-size="14" font-family="system-ui">{value:.0}</text>"##,
        y = y,
        bar_y = bar_y,
        bar_width = bar_width,
        filled = filled,
        bar_color = bar_color,
        label = label,
        value = value,
    )
}

/// 전체 SVG 리포트 이미지 생성
pub fn render_svg(score: &VibeScore, analysis: &AnalysisResult) -> String {
    let accent = grade_color(&score.grade);
    let grade_str = score.grade.to_string();

    let bars = [
        ("Commit Frequency", score.commit_frequency),
        ("Hotspot Health", score.hotspot_score),
        ("Ghost Files", score.ghost_score),
        ("Commit Mood", score.mood_score),
        ("Bus Factor", score.bus_factor_score),
        ("Activity Trend", score.trend_score),
    ];

    let mut bar_svgs = String::new();
    for (i, (label, value)) in bars.iter().enumerate() {
        let y = 220 + (i as u32 * 28);
        bar_svgs.push_str(&score_bar_svg(label, *value, y, accent));
        bar_svgs.push('\n');
    }

    // 감정 바: 가로 비율 막대
    let mood = &analysis.mood;
    let mood_segments = [
        ("\u{1f60a}", mood.happy, "#9ece6a"),
        ("\u{1f630}", mood.stressed, "#e05d44"),
        ("\u{1f9f9}", mood.cleanup, "#7aa2f7"),
        ("\u{1f480}", mood.scary, "#9f9f9f"),
        ("\u{1f937}", mood.other, "#565f89"),
    ];

    let mut mood_bar = String::new();
    let mood_bar_width = 400u32;
    let mut mood_x = 40u32;
    let mood_y = 410u32;
    for (emoji, ratio, color) in &mood_segments {
        let w = (*ratio * mood_bar_width as f64).round() as u32;
        if w > 0 {
            mood_bar.push_str(&format!(
                r#"  <rect x="{mx}" y="{my}" width="{w}" height="18" fill="{color}"/>
  <text x="{tx}" y="{ty}" fill="white" font-size="11" font-family="system-ui">{emoji} {pct:.0}%</text>
"#,
                mx = mood_x,
                my = mood_y,
                w = w,
                color = color,
                tx = mood_x + 2,
                ty = mood_y + 14,
                emoji = emoji,
                pct = ratio * 100.0,
            ));
        }
        mood_x += w;
    }

    format!(
        r##"<svg xmlns="http://www.w3.org/2000/svg" width="800" height="480" viewBox="0 0 800 480">
  <rect width="800" height="480" rx="16" fill="#1a1b26"/>

  <!-- Header -->
  <text x="40" y="45" fill="#7aa2f7" font-size="22" font-weight="bold" font-family="system-ui">🎭 Vibe Check: {repo_name}</text>
  <line x1="40" y1="60" x2="760" y2="60" stroke="#7aa2f7" stroke-width="2"/>

  <!-- Grade -->
  <text x="40" y="100" fill="{accent}" font-size="28" font-weight="bold" font-family="system-ui">Overall Vibe: {grade}</text>
  <text x="40" y="130" fill="#565f89" font-size="16" font-family="system-ui">Score: {score:.0}/100</text>

  <!-- Stats -->
  <text x="40" y="165" fill="#c0caf5" font-size="14" font-family="system-ui">📊 Period: {period}  |  Commits: {commits}  |  Files: {files}</text>

  <!-- Separator -->
  <line x1="40" y1="180" x2="760" y2="180" stroke="#2a2b3d" stroke-width="1"/>

  <!-- Score Bars -->
  <text x="40" y="205" fill="#7aa2f7" font-size="16" font-weight="bold" font-family="system-ui">📈 Sub Scores</text>
{bars}
  <!-- Mood -->
  <text x="40" y="395" fill="#7aa2f7" font-size="16" font-weight="bold" font-family="system-ui">🎭 Commit Mood</text>
{mood_bar}
  <!-- Footer -->
  <line x1="40" y1="445" x2="760" y2="445" stroke="#2a2b3d" stroke-width="1"/>
  <text x="40" y="468" fill="#565f89" font-size="12" font-family="system-ui">Generated by git-vibe · github.com/calintzy/git-vibe</text>
</svg>"##,
        repo_name = xml_escape(&analysis.repo_name),
        accent = accent,
        grade = xml_escape(&grade_str),
        score = score.total,
        period = xml_escape(&analysis.period_label),
        commits = analysis.total_commits,
        files = analysis.total_files,
        bars = bar_svgs,
        mood_bar = mood_bar,
    )
}

/// PNG 변환 (resvg feature flag 필요)
#[cfg(feature = "png")]
pub fn save_as_png(svg_content: &str, path: &std::path::Path) -> Result<(), crate::error::VibeError> {
    use resvg::tiny_skia;
    use resvg::usvg;

    let opt = usvg::Options::default();
    let tree = usvg::Tree::from_str(svg_content, &opt)
        .map_err(|e| crate::error::VibeError::Git(format!("SVG 파싱 오류: {}", e)))?;

    let size = tree.size();
    let width = size.width() as u32;
    let height = size.height() as u32;

    let mut pixmap = tiny_skia::Pixmap::new(width, height)
        .ok_or_else(|| crate::error::VibeError::Git("PNG 버퍼 생성 실패".to_string()))?;

    resvg::render(&tree, tiny_skia::Transform::default(), &mut pixmap.as_mut());

    pixmap.save_png(path)
        .map_err(|e| crate::error::VibeError::Io(
            std::io::Error::new(std::io::ErrorKind::Other, e.to_string())
        ))
}

#[cfg(not(feature = "png"))]
pub fn save_as_png(_svg_content: &str, _path: &std::path::Path) -> Result<(), crate::error::VibeError> {
    Err(crate::error::VibeError::Git(
        "PNG 지원은 'png' feature가 필요합니다. `cargo install git-vibe --features png`로 설치하세요".to_string()
    ))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::scoring::grades::VibeGrade;

    #[test]
    fn test_grade_color_mapping() {
        assert_eq!(grade_color(&VibeGrade::Zen), "#4c1");
        assert_eq!(grade_color(&VibeGrade::Chill), "#97CA00");
        assert_eq!(grade_color(&VibeGrade::Abandoned), "#9f9f9f");
    }

    #[test]
    fn test_xml_escape() {
        assert_eq!(xml_escape("a<b>c&d\"e"), "a&lt;b&gt;c&amp;d&quot;e");
        assert_eq!(xml_escape("hello"), "hello");
    }

    #[test]
    fn test_score_bar_svg_contains_elements() {
        let svg = score_bar_svg("Test Label", 75.0, 100, "#ff0000");
        assert!(svg.contains("Test Label"));
        assert!(svg.contains("75"));
        assert!(svg.contains("#ff0000"));
    }

    #[test]
    fn test_render_svg_contains_structure() {
        let score = VibeScore {
            total: 74.0,
            grade: VibeGrade::Active,
            commit_frequency: 80.0,
            hotspot_score: 72.0,
            ghost_score: 85.0,
            mood_score: 65.0,
            bus_factor_score: 50.0,
            trend_score: 60.0,
        };
        let analysis = crate::git::AnalysisResult {
            repo_name: "test-repo".to_string(),
            period_label: "6m".to_string(),
            total_commits: 100,
            total_files: 50,
            hotspots: vec![],
            ghosts: vec![],
            mood: crate::git::mood::MoodStats {
                happy: 0.45,
                stressed: 0.32,
                cleanup: 0.18,
                scary: 0.05,
                other: 0.0,
                total_commits: 100,
            },
            authors: vec![],
            bus_factor: 3,
            monthly_activity: vec![],
            commits: vec![],
        };

        let svg = render_svg(&score, &analysis);
        assert!(svg.contains("<svg"));
        assert!(svg.contains("test-repo"));
        assert!(svg.contains("Commit Frequency"));
        assert!(svg.contains("Commit Mood"));
        assert!(svg.contains("Generated by git-vibe"));
    }
}
